### ISSUE TITLE
Multiple Preview Fields

### ISSUE THREAD

**Issue by uxder** [grow/grow-ext-editor#118] opened 2020-12-11 19:01 UTC
A given module maybe have optional fields - such as a title and body.  

```
chapter:
    title: ''
    body: world
```

Can we define multiple preview_fields in order of preference so that if one is empty, it falls back to the next.

```
preview_field: chapter.title | chapter.body

or 

preview_fields: 
- chapter.title 
- chapter.body

```

**Comment by Zoramite** [comment] 2020-12-11 19:19
Duplicate of #110

**Closed by Zoramite** 2020-12-11 19:19 UTC
